project_id = "qfyvgpgsyzygivopekfa"

[functions.submit-intake]
verify_jwt = false


[functions.sol-alert-emailer]
verify_jwt = false

[functions.patient-engagement-reminders]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
