DROP VIEW IF EXISTS public.cases_with_counts;

CREATE VIEW public.cases_with_counts
WITH (security_invoker=on) AS
SELECT c.id,
    c.case_number,
    c.patient_name,
    c.patient_phone,
    c.patient_email,
    c.status,
    c.flag,
    c.specialty,
    c.accident_date,
    c.accident_state,
    c.opened_date,
    c.sol_period_days,
    c.sol_date,
    c.lien_amount,
    c.settlement_estimate,
    c.settlement_final,
    c.attorney_id,
    c.provider_id,
    c.notes,
    c.created_at,
    c.updated_at,
    c.request_date,
    c.preferred_language,
    c.initial_appointment_date,
    c.initial_appointment_status,
    c.marketer_id,
    c.case_manager_email,
    c.case_manager_phone,
    c.law_firm_website,
    c.completeness_score,
    c.quality_gate_passed,
    c.marketplace_submitted_at,
    c.marketplace_accepted_at,
    c.urgent,
    c.marketer_consent_signed,
    c.marketer_consent_signed_at,
    count(a.id) AS appointments_total,
    count(a.id) FILTER (WHERE a.status = 'Completed'::text) AS appointments_completed
   FROM cases c
     LEFT JOIN appointments a ON a.case_id = c.id
  GROUP BY c.id;